### ISSUE TITLE
sharp-blockhash doesn't works in Google Cloud Functions

### ISSUE THREAD

**Issue by wiliame** [andyhu/sharp-blockhash#1]
In GCF it installs the version 0.15 of sharp that doesn't work, it outputs the next error message:

"Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory"

But sharp 0.18.2 works fine in GCF.

**Comment by wiliame** [comment]
It's enough with updating sharp to 0.18.2.

**Comment by andyhu** [comment]
Hi, thanks for your comment, I'll update it
